[ssopms]
10.164.1.XXX

[ssopms:vars]
ansible_user=martin.lord
ansible_ssh_private_key_gitea=~/.ssh/id_ed25519
ansible_ssh_private_key_stash=~/.ssh/id_ed25519
ansible_ssh_private_key_GHEC=~/.ssh/id_ed25519_GHEC
ansible_ssh_private_key_github_HPE=~/.ssh/id_ed25519_github_hpe
ansible_python_interpreter=/usr/bin/python3
build_env=~/.env
base_dir=/mnt/work/cnx-lite
docker_dir=/mnt/work/containerd
